### ISSUE TITLE
ERROR: object 'non_data_cols' not found

### ISSUE THREAD

**Issue by ManoharSwamynathan** [mchernos/ModelBuilder1.0#1]
Hi Matt,

This project looks very interesting.

I'm getting the error "ERROR: object 'non_data_cols' not found" while trying to run the code remotely.

Regards,
Manohar

**Comment by mchernos** [comment]
Hey Manohar. Looks like there's something about how I've organized the working directories that running the app through GitHub doesn't like... Let me know if it doesn't work offline -- it does on my end...

Cheers,

Matt

**Comment by mchernos** [comment]
Should be good to go now. The helper.R needed to be sourced in both the UI and server files (since the UI uses 'non_data_cols'.

Cheers,

Matt
